# Use an official Node runtime as a parent image
FROM node:20

# Set the working directory to /app
WORKDIR /app


# Copy the current directory contents into the container at /app
COPY . /app

copy package.json /app

# Install any needed packages specified in package.json
RUN npm install

RUN npm install -g @angular/cli

# Set the default command to run ng serve
CMD ["npm", "run", "dev"]
