# Use an official Node runtime as a parent image
FROM node:20 as dev

# Set the working directory to /app
WORKDIR /app

# Install Angular CLI
RUN npm install -g @angular/cli

copy package.json /app
copy frontend/package.json /app/frontend/package.json
copy api/package.json /app/api/package.json


# Install any needed packages specified in package.json
RUN npm install


# Copy the current directory contents into the container at /app
COPY . /app


# Set the default command to run ng serve
CMD ["npm", "run", "dev"]




# this is another docker image layer based on the dev from above,
# this image will be used for the prod container
from dev as prod

# run build command with 512 memory limit in container
RUN npm run build

CMD [ "npm", "run", "start" ]

